### ISSUE TITLE
Documentation says nothing about non-identical but overlapping separators

### ISSUE THREAD

**Issue by AnthonyMikh** [veeso/range-parser#3]
This test currently fails:

```rust
#[test]
fn ambiguous() {
    range_parser::parse_with::<u8>("0-11--13", "-", "--").unwrap();
}
```

I think that it should either work as intended (return `Ok(vec![0, 11, 12, 13])`) or to be documented to not to support such degenerate cases.

**Comment by veeso** [comment]
I've opted to return an error, since it's too ambiguous and would not behave as expected with negative numbers. babc9732
